seed: 12
model_checkpoint: null

base_lr: 4.5e-6
batch_size: 12
epochs: 10
steps_per_epoch: 0

model: ???
quantizer: ???
discriminator: null

optimizer:
  factory: torch.optim.AdamW
  eps: 1e-8
  betas: [0.5, 0.9]
  weight_decay: 0.0

rampup: 200
cosine_annealing: True
clip_grad_norm: null

adv_start_step: 0

loss_weights:
  pixel: 1.0
  perceptual: 1.0
  adv: 0.8

pixel_loss: torch.nn.L1Loss
perceptual_loss: null
adv_loss: softfsq.losses.GeneratorWGANLoss
disc_loss: softfsq.losses.DiscriminatorHingeLoss

compile: True
profile: False
wandb: softfsq-imagenet
checkpointing: True
